### ISSUE TITLE
仿真的时候遇到一些问题

### ISSUE THREAD

**Issue by Aaricis** [SwarmRoboticsSUSTechOPAL/swarm_robot_formation#1]
你好！我在仿真的时候，找不到”turtlebot3_simulations turtlebot3_world.launch“和”turtlebot3_simulations turtlebot3_model.launch（model.rviz）“文件。
请问， ”turtlebot3_world.launch“是这个项目的地图吗？在项目里找不到。
还有，我不懂仿真时为什么要修改机器人的编号？

**Comment by Gaoee** [comment]
这些文件是在turtlebot3_simulations包https://github.com/SwarmRoboticsSUSTech/turtlebot3_simulations_sustc中的
地图在https://github.com/SwarmRoboticsSUSTech/turtlebot_maps
修改机器人的编号是为了防止ros中的节点冲突
建议你最好还是在真实机器人上做测试，我们并没有做多机器人的仿真环境，你需要自己开发多机器人的仿真环境才能进行测试

**Comment by Aaricis** [comment]
谢谢您的回复！感激涕零！
我试着仿真这个已经好几天了
我是新手，这个项目对我的帮助特别大。
