### ISSUE TITLE
仿真遇到问题

### ISSUE THREAD

**Issue by Aaricis** [SwarmRoboticsSUSTechOPAL/swarm_robot_formation#2]
![2018-04-03 19-07-26](https://user-images.githubusercontent.com/35218694/38245739-f29bb196-3771-11e8-95dc-5eeda38faef3.png)
你好，遇到这样的错误，我不知道怎么解决了。

**Comment by Gaoee** [comment]
不好意思，turtlebot3_model.launch是在turtlebot3_bringup包中的
roslaunch turtlebot3_bringup turtlebot3_model.launch

**Comment by Gaoee** [comment]
做多机器人的gazebo仿真，你可以去了解下这个包：https://github.com/hasauino/rrt_exploration_tutorials

**Comment by Aaricis** [comment]
谢谢指点！
你还能特地告诉我，真是太感动了
